myapp/infsoc/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import include

from . import views

urlpatterns = [
    #home
    path('', views.home, name='home'),
	path('accounts/', include('django.contrib.auth.urls')),

    path('login/', views.login, name='login'),

    
    path('buscador/', views.buscador, name='buscador'),
    path('buscador/<int:id_transaccion>', views.buscar, name='buscar'),

    path('crear/', views.crearTransaccion, name='crear'),

    path('transacciones/', views.transacciones, name='transacciones'),

]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('infsoc/', include('infsoc.urls')),
]

myapp/infsoc/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime  

class Medicamento(models.Model):
	nombre = models.CharField(max_length=255)
	miligramos = models.IntegerField()

	def __str__(self):
		return self.nombre + ' ' + str(self.miligramos) + ' mg'


class Comuna(models.Model):
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

class Linea(models.Model):
	numero = models.IntegerField(unique=False, blank=True)
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

	class Meta:
		ordering = ['numero']

class Metro(models.Model):
	numero = models.IntegerField(default=1)
	nombre = models.CharField(max_length=255)
	linea = models.ForeignKey(Linea, on_delete=models.CASCADE)
	comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return self.nombre

	class Meta:
		ordering = ['numero']

class Transaccion(models.Model):
	ESTADO = (
	    ('PUESTO', 'PUESTO'),
	    ('CONTACTADO','CONTACTADO'),
	    ('LISTO', 'LISTO'),
	)

	TIPO = (
		('VENTA', 'VENTA'),
		('COMPRA', 'COMPRA'),
		('REGALO', 'REGALO'),
	)

	medicamento = models.ForeignKey(Medicamento, on_delete=models.CASCADE, null=False, blank=False)
	vendedor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='vendedor')
	comprador = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='comprador')
	tipo = models.CharField(max_length=255, choices=TIPO)
	estado = models.CharField(max_length=255, choices=ESTADO, default='PUESTO')
	precio = models.IntegerField(default=0)
	comunas = models.ManyToManyField(Comuna, null=True, blank=True)
	lineas = models.ManyToManyField(Linea)
	fecha = models.DateTimeField(auto_now_add=True, blank=True)

	def __str__(self):
		if self.vendedor is None:
			return self.comprador.first_name + ' ' + self.tipo + ' ' + str(self.medicamento) + ' ' + self.estado
		else:
			return self.vendedor.first_name + ' ' + self.tipo + ' ' + str(self.medicamento) + ' ' + self.estado

myapp/infsoc/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class TransaccionForm(ModelForm):

	class Meta:
		model = Transaccion
		fields = ['tipo', 'precio', 'lineas']
		help_texts = {
			'lineas': 'Mantenga control apretado para elegir más de una línea.',
			'tipo': 'Tipo de transacción: venta, compra o regalo.',
		}

class LoginForm(forms.Form):
	usuario = forms.CharField()
	password = forms.CharField(label='Contraseña',widget=forms.PasswordInput)

myapp/infsoc/views.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response, redirect
from django.db.models import Q

from .forms import *
from .models import *

from django.contrib.auth import login as auth_login, authenticate
from django.core.serializers.json import DjangoJSONEncoder
from django.http import JsonResponse
from django.http import HttpResponse
import json

# Create your views here.
def home(request):
	template = 'infsoc/home.html'

	return render(request, template, {})

def login(request):
	
	template = 'infsoc/login.html'
	
	if request.method == 'POST':
		print (request.POST)
		form = LoginForm(request.POST)
		if form.is_valid():
			user = form.cleaned_data.get('usuario')
			password = form.cleaned_data.get('password')
			user = authenticate(request, username=user, password=password)
			if user is not None:
				auth_login(request, user)
				return redirect('home')
			else:
				return render(request, template, {'form':form, 
										'error': 'usuario no encontrado'})
	
	form = LoginForm()

	return render(request, template, {'form':form})

def buscador(request):

	template = 'infsoc/buscador.html'
	form = TransaccionForm()

	if request.method == "POST":
		
		medicamento = request.POST.get('search_field').split()[0]
		print(Medicamento)
		if Medicamento.objects.filter(nombre=medicamento).count() > 0:
			med = Medicamento.objects.get(nombre = request.POST.get('search_field').split()[0])
			tipo = request.POST.get('tipo')
			lineas = request.POST.getlist('lineas')

			tr = Transaccion.objects.filter(medicamento=med, tipo=tipo, estado="PUESTO")
			print(tr)
			exclude_list = []
			for trans in tr:
				l = trans.lineas.all()
				for item in l:
					if str(item.id) in lineas:
						#print(item)
						break
				exclude_list.append(item.id)
			if len(exclude_list) > 0:
				tr = Transaccion.objects.filter(medicamento=med, tipo=tipo, estado="PUESTO").exclude(id__in=exclude_list)
				print(tr)

			return render(request, template, {'transacciones': tr})

			#return buscar(request, medicamento)	

		medicamentos = Medicamento.objects.all()
		medicamentos_list = []
		for medicamento in medicamentos:
			medicamentos_list.append(str(medicamento))

		json_medicamento = json.dumps(medicamentos_list)
		#print(json_alimentos)

		return render(request, template, {'medicamentos':json_medicamento ,
								          'error': 'no se encontro el medicamento',
								          'form': form})


	medicamentos = Medicamento.objects.all()
	medicamentos_list = []
	for medicamento in medicamentos:
		medicamentos_list.append(str(medicamento))

	json_medicamento = json.dumps(medicamentos_list)
	#print(json_alimentos)

	return render(request, template, {'medicamentos':json_medicamento, 
									  'form': form})


def buscar(request, id_transaccion):
	print('Llegue!')

	template = 'infsoc/transaccion.html'

	tr = Transaccion.objects.get(id=id_transaccion)

	if request.method == "POST":
		if tr.tipo in ["VENTA", "REGALO"]:
			tr.comprador = request.user
			tr.estado = 'CONTACTADO'
			tr.save()
			return render(request, template, {'aprobado': 'Transacción completada, favor contactarse con ' +str(tr.vendedor.first_name)})

		elif tr.tipo == "COMPRA":
			tr.vendedor = request.user
			tr.estado = 'CONTACTADO'
			tr.save()
			return render(request, template, {'aprobado': 'Transacción completada, favor contactarse con ' +str(tr.comprador.first_name)})

		else:
			return HttpResponse('Error!')



	return render(request, template, {'transaccion': tr})

def crearTransaccion(request):

	template = 'infsoc/crearTransaccion.html'

	if request.method == "POST":
		#print(request.POST.get('search_field').split()[0])
		#print(request.POST)
		medicamento = Medicamento.objects.get(nombre = request.POST.get('search_field').split()[0])
		tipo = request.POST.get('tipo')
		lineas = request.POST.getlist('lineas')
		precio = request.POST.get('precio')
		print(lineas)
		#print(medicamento)

		if tipo == "COMPRA":
			comprador = request.user
			#print(comprador)
			t = Transaccion(medicamento=medicamento,
							comprador=comprador,
							tipo=tipo)
			t.save()
			for linea in lineas:
				t.lineas.add(linea)
			t.save()

			return render(request, template, {'aprobado': 'Transacción para ' + str(medicamento) + ' creada correctamente.'})


		elif tipo == "VENTA":
			vendedor = request.user
			#print(vendedor)
			t = Transaccion(medicamento=medicamento,
							vendedor=vendedor,
							tipo=tipo,
							precio=precio)
			t.save()
			for linea in lineas:
				t.lineas.add(linea)
			t.save()

			return render(request, template, {'aprobado': 'Transacción para ' + str(medicamento) + ' creada correctamente.'})

		elif tipo == "REGALO":
			regalador = request.user
			t = Transaccion(medicamento=medicamento,
							vendedor=regalador,
							tipo=tipo,
							precio=0)
			t.save()
			for linea in lineas:
				t.lineas.add(linea)
			t.save()

			return render(request, template, {'aprobado': 'Transacción para ' + str(medicamento) + ' creada correctamente.'})


		


	"""
	medicamento = models.ForeignKey(Medicamento, on_delete=models.CASCADE, null=False, blank=False)
	vendedor = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, related_name='vendedor')
	comprador = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, related_name='comprador')
	tipo = models.CharField(max_length=255, choices=TIPO)
	estado = models.CharField(max_length=255, choices=ESTADO, default='PENDIENTE')
	precio = models.IntegerField(null=True, blank=True)
	comunas = models.ManyToManyField(Comuna, null=False, blank=False)
	lineas = models.ManyToManyField(Linea)
	fecha = models.DateTimeField(auto_now_add=True, blank=True)
	"""

	form = TransaccionForm()
	medicamentos = Medicamento.objects.all()
	medicamentos_list = []
	for medicamento in medicamentos:
		medicamentos_list.append(str(medicamento))

	json_medicamento = json.dumps(medicamentos_list)
	#print(json_alimentos)

	return render(request, template, {'medicamentos':json_medicamento,
									  'form': form})


def transacciones(request):

	template = 'infsoc/transacciones.html'

	tr = Transaccion.objects.filter(Q(comprador=request.user) | Q(vendedor=request.user)).order_by('estado')

	return render(request, template, {'transacciones1': tr })

myapp/infsoc/templates/infsoc/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block headcontent %}
    {% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>LupusHelper</title>
    <style type="text/css">
      <style>

p {
    font-size: 1.1em;
    font-weight: 300;
    line-height: 1.7em;
    color: #999;
}


/* SIDEBAR STYLE */

#sidebar {
    width: 200px;
    position: fixed;
    top: 100px;
    left: 0;
    height: 100vh;
    z-index: 999;
    background: #5f0f82;
    color: #fff;
    transition: all 0.3s;
}

#sidebar .sidebar-header {
    padding: 20px;
    background: #9013c6;
    text-align: center;
}


#sidebar ul p {
    color: #fff;
    padding: 10px;
}

#sidebar ul li a {
    padding: 10px;
    font-size: 1.1em;
    display: block;
}
#sidebar ul li a:hover {
    color: #9013c6;
    background: #fff;
}

#sidebar ul li a, ul li a:hover, ul li a:focus {
    color: inherit;
    text-decoration: none;
    transition: all 0.3s;
}
.dropright:click{

}
.dropright:hover .dropdown-menu {
    display: block;
    margin-top: 0; // remove the gap so it doesn't close
 }

.page-header{
    height: 100px;
    width: 100%;
    position: fixed;
    top: 0;
    left: 0;
    z-index: 999;
    background: #5f0f82;
    color: #fff;
}
.page-header h1{
  font-size: 60px;
  text-align: center;
  padding: 10px 0;
}
.page-header p{
  font-size: 15px;
  text-align: center;
  margin-top: -35px; 
}

.logout {
  margin-top: 200px;
}
/* ---------------------------------------------------
    CONTENT STYLE
----------------------------------------------------- */
#content {
    width: calc(100% - 200px);
    padding: 40px;
    min-height: 100vh;
    transition: all 0.3s;
    position: absolute;
    top: 100px;
    right: 0;
}

</style>
  </head>
    <body>
        <div class="navbar">
          <div class="page-header">
            <h1>LupusHelper</h1>
            <p>Transacciones de medicamentos a falta de ges.</p>
          </div>

            <!-- Sidebar Holder -->
            <nav id="sidebar">
              {% if user.is_authenticated %}
              <div class="sidebar-header">
                  <h3>Bienvenido</h3>
                  <p style="font-size: 20px">{{ user.first_name }}</p>
              </div>
              <ul class="list-unstyled components">
                 <ul class="list-unstyled components">
                    <li>
                      <a href="">Ver perfil</a>
                    </li>
                    <li>
                      <a href="{% url 'crear' %}">
                        Publicar medicamento
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'buscador' %}">Buscar Medicamento</a>
                    </li>
                    <li>
                      <a href="{% url 'transacciones' %}">Ver transacciones</a>
                    </li>
                    <li class="logout">
                      <a href="{% url 'logout' %}">Cerrar sesión</a>
                    </li>
                </ul>
              </ul>
              {% else %}
              <ul class="list-unstyled components" style="margin-top: 100px">
                <ul class="list-unstyled components">
                    <li>
                      <a href="{% url 'login' %}">Ingresar</a>
                    </li>
                </ul>
              </ul>
              {% endif %}
            </nav>

            <!-- Page Content Holder -->
            <div id="content">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                    <!-- Dentro de este bloque irá todo lo otro -->
                    {% block content %}
                    {% endblock %}                
                    </div>
                </nav>
            </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  </body>
</html>

myapp/infsoc/templates/infsoc/buscador.html
{% extends "infsoc/base.html" %}

{% block headcontent %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
  	//console.log('hola')
  	//console.log({{ medicamentos|safe }});
    var availableTags = {{ medicamentos|safe }};
    $( "#search_field" ).autocomplete({
      source: availableTags
    });
  } );
  </script>

{% endblock %}

{% block content %}

<style type="text/css">
.form-control{
	width: 400px;
}	
</style>
{% if transacciones %}
	<div class="container-fluid">
			<div class="row" style="font-weight: bold" style="margin-bottom: 30px;">
				<div class="col"> Medicamento </div>
				<div class="col"> Precio </div>
				<div class="col"> Líneas del metro </div>
				<div class="col"> Fecha </div>
			</div>
			{% for transaccion in transacciones %}
				<div class="row">
					<div class="col"><a href="{% url 'buscar' transaccion.id %}"> {{transaccion.medicamento}} </a></div>
					<div class="col"> {{transaccion.precio}} </div>
					<div class="col"> {% for linea in transaccion.lineas.all %}
								{{linea.numero}} 
							  {% endfor %} </div>
					<div class="col"> {{transaccion.fecha}} </div>
				</div>
			{% endfor %}
	</div>
{% else %}
<div class="container" style="margin-left: 20px" >
	<h2>Búsqueda de medicamento</h2>
	<hr>
	<form class="form-horizontal" method="post">
		{% csrf_token %}
		<div class="form-group">
            <label class="control-label col-sm-2" style="font-weight: bold;">Medicamento: </label>
            <div class="col-sm-10">
            	<input id="search_field" name="search_field" class="form-control" type="text" placeholder="Ejemplo: Plaquinol 40 mg" aria-label="Search" required>
            	<p style="font-size: 10px; color: gray;">Ingrese medicamento a buscar.</p>
            </div>
        </div>
        {% for field in form %}
    	{% if field.label != 'Precio' %}
        	<div class="form-group" style="margin-bottom: 20px">
        		<label class="control-label col-sm-2" style="font-weight: bold;"> {{field.label}} </label>
        		<div class="col-sm-10">
        			{{field}}
        			{% if field.help_text %}
        				<p style="font-size: 10px; color: gray;">{{field.help_text|safe}}</p>
        			{% endif %}
        		</div>
        	</div>
        {% endif %}
        {% endfor %}
        <div class="col-md-4 text-left"> 
	  		<button type="submit" class="btn btn-primary" style="margin: auto;">Buscar</button>
		</div>
	</form>
</div>

{% endif %}
{% endblock %}

myapp/infsoc/templates/infsoc/crearTransaccion.html
{% extends "infsoc/base.html" %}

{% block headcontent %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
  	//console.log('hola')
  	//console.log({{ medicamentos|safe }});
    var availableTags = {{ medicamentos|safe }};
    $( "#search_field" ).autocomplete({
      source: availableTags
    });
  } );
  $(document).ready( function(){
  		if($("#id_tipo").val() != 'VENTA'){
			document.getElementById("id_precio").readOnly = true;
		}
		$("#id_tipo").on('change', function(){
			if($("#id_tipo").val() == 'VENTA'){
				document.getElementById("id_precio").readOnly = false;
			}
			else{
				document.getElementById("id_precio").readOnly = true;
			}
		});
	});
  </script>
  <style type="text/css">
	.form-control{
		width: 400px;
	}	
</style>

{% endblock %}

{% block content %}
{% if aprobado %}
<div class="container" style="margin-left: -20px" >
<p>{{aprobado}}</p>
    <div class="col-md-4 text-left"> 
  		<a class="btn btn-primary" onclick="relocate()">Volver</a>
    </div>
</div>
<script>
function relocate() {
  location.href = {% url 'home' %};
}
</script>
{% else %}

<div class="container" style="margin-left: 20px" >
	<h2>Crear Transacción</h2>
	<hr>
	<form class="form-horizontal" method="post">
		{% csrf_token %}
		<div class="form-group">
            <label class="control-label col-sm-2" style="font-weight: bold;">Medicamento: </label>
            <div class="col-sm-10">
            	<input id="search_field" name="search_field" class="form-control" type="text" placeholder="Ejemplo: Plaquinol 40 mg" aria-label="Search" required>
            	<p style="font-size: 10px; color: gray;">Ingrese medicamento a buscar.</p>
            </div>
        </div>
        {% for field in form %}
        	<div class="form-group" style="margin-bottom: 20px">
        		<label class="control-label col-sm-2" style="font-weight: bold;"> {{field.label}} </label>
        		<div class="col-sm-10">
        			{{field}}
        			{% if field.help_text %}
        				<p style="font-size: 10px; color: gray;">{{field.help_text|safe}}</p>
        			{% endif %}
        		</div>
        	</div>
        {% endfor %}
        <div class="col-md-4 text-left"> 
	  		 <button type="submit" class="btn btn-primary" style="margin: auto;">Crear publicación</button>
		    </div>
	</form>
</div>
{% endif %}
{% endblock %}

myapp/infsoc/templates/infsoc/home.html
{% extends "infsoc/base.html" %}
{% block content %}

<p>
  Lupus helper es un servicio para ajustar el desequilibrio que exite hoy en día en la distribución de remedios
  ofrecidos por la canasta GES para la gente que pacede Lupus.
</p>
<p>
  Para hacer uso de este servicio basta con que crees una transacción con los remedios que te falten o que te sobren.
  Si deseas buscar uno, ingresa al buscador.
</p>
<p>
  Para ver todas las transacciones que has realizado y ver su estado, ingresa a la opción del menú ver transacciones.
</p>
{% endblock %}

myapp/infsoc/templates/infsoc/login.html
{% extends "infsoc/base.html" %}
{% block content %}

<div class="container" style="margin-left: -20px">
<form class="form-horizontal" method="post">
  {% csrf_token %}
    {% for field in form %}
          <div class="form-group" style="margin-bottom: 20px">
            <label class="control-label col-sm-2" style="font-weight: bold;"> {{field.label}} </label>
              {{field}}
          </div>
        {% endfor %}
    <div class="col-md-4 text-left"> 
        <button type="submit" class="btn btn-primary" style="margin: auto;">Ingresar</button>
    </div>
</form>
</div>
{% endblock %}

myapp/infsoc/templates/infsoc/transaccion.html
{% extends "infsoc/base.html" %}


{% block content %}

{% if aprobado %}
	<p>{{aprobado}}</p>

{% else %}
	<div class="container">
		<h3>Detalle transacción</h3>
		<hr>

		<div class="row">
			<div class="col-sm-2">Medicamento: </div>
			<div class="col-sm-3">{{transaccion.medicamento}}</div>
		</div>

		<div class=row>
			{% if transaccion.tipo == 'COMPRA' %}	
			<div class="col-sm-2">Comprador: </div>
			<div class="col-sm-3">
				{{ transaccion.comprador.first_name }} {{ transaccion.comprador.last_name }} 
			</div>
			{% else %}
				<div class="col-sm-2">Vendedor: </div>
				<div class="col-sm-3">
				{{ transaccion.vendedor.first_name }} {{ transaccion.vendedor.last_name }}
			</div>
			{% endif %}
		</div>	
		<div class=row>
			<div class="col-sm-2">Correo: </div>
			{% if transaccion.tipo == 'COMPRA' %}	
			<div class="col-sm-3">
				{{ transaccion.comprador.email }}
			</div>
			{% else %}
				<div class="col-sm-3">
				{{ transaccion.vendedor.email }}
			</div>
			{% endif %}
		</div>	
		<div class="row">
			<div class="col-sm-2">Precio: </div>
			<div class="col-sm-3">${{transaccion.precio}}</div>
		</div>
		<div class="row">
			<div class="col-sm-2">Líneas de metro: </div>
			<div class="col-sm-3">{% for linea in transaccion.lineas.all %}
								{{ linea.numero }} 
								{% endfor %}
			</div>
		</div>
		<hr>
		<form method="POST">
			{% csrf_token %}
			<div class="row">
		        <div class="col-md-4 text-left"> 
			  		 <button type="submit" class="btn btn-primary" style="margin: auto;">Hacer pedido</button>
				</div>
			</div>
		</form>
	</div>
{% endif %}

{% endblock %}

myapp/infsoc/templates/infsoc/transacciones.html
{% extends "infsoc/base.html" %}


{% block content %}

<div class="container-fluid" style="margin-left: 20px;">
	<h3>Tus transacciones</h3>
	<hr>
		<div class="row" style="font-weight: bold" style="margin-bottom: 30px;">
			<div class="col"> Medicamento </div>
			<div class="col"> Persona </div>
			<div class="col"> Email </div>
			<div class="col"> Tipo de transacción </div>
			<div class="col"> Fecha de la publicación</div>
			<div class="col"> Estado </div>
		</div>
		{% for transaccion in transacciones1 %}
			<div class="row">
				<div class="col"> {{transaccion.medicamento}} </a></div>
				{% if transaccion.tipo == "COMPRA" %}
					{% if transaccion.vendedor == user %}	
						<div class="col"> {{transaccion.comprador.first_name}} </div>
						<div class="col"> {{transaccion.comprador.email}} </div>
					{% else %}
						<div class="col"> {{transaccion.vendedor.first_name}} </div>
						<div class="col"> {{transaccion.vendedor.email}} </div>
					{% endif %}
				{% else %}
					{% if transaccion.vendedor == user %}
					 	<div class="col"> {{transaccion.comprador.first_name}} </div>
					 	<div class="col"> {{transaccion.comprador.email}} </div>
					{% else %}
						<div class="col"> {{transaccion.vendedor.first_name}} </div>
						<div class="col"> {{transaccion.vendedor.email}} </div>
					{% endif %}
				{% endif %}
				<div class="col"> {{transaccion.tipo}} </div>
				<div class="col"> {{transaccion.fecha}} </div>
				<div class="col" style="color: {% if transaccion.estado == "PUESTO" %}
												red;"
											   {% elif transaccion.estado == "CONTACTADO" %}
											    orange;"
											   {% else %}
											    green;"
											   {% endif %}
				> {{transaccion.estado}} </div>
			</div>
		{% endfor %}
</div>

{% endblock %}